// src/data/meals.ts
import type { Meal } from "@/types/meal";

/**
 * Initial MVP dataset — ~50 Nigeria-first meals.
 * Costs are rough estimates for a single serving (homemade), not live market prices.
 */
export const MEALS: Meal[] = [
  // ───────────── RICE ─────────────
  {
    id: "egg-fried-rice",
    name: "Egg Fried Rice",
    description: "Rice tossed with egg, onion and pepper. Fast, filling and forgiving.",
    ingredients: ["rice", "egg", "onion", "pepper", "carrot", "oil", "seasoning"],
    estimatedCostNgn: 1500,
    cookingTimeMinutes: 25,
    difficulty: "easy",
    moods: ["quick", "hungry", "budget", "tired"],
    mealTimes: ["lunch", "dinner"],
    instructions: [
      "Boil the rice and set it aside.",
      "Heat oil, fry the onion and pepper for 2 minutes.",
      "Pour in the beaten egg and scramble it.",
      "Add the rice, carrot and seasoning. Stir well.",
      "Cover and steam for 3 minutes, then serve.",
    ],
  },
  {
    id: "simple-jollof-rice",
    name: "Simple Jollof Rice",
    description: "The classic. Smoky tomato rice that always delivers.",
    ingredients: ["rice", "tomato", "pepper", "onion", "oil", "seasoning", "curry"],
    estimatedCostNgn: 1800,
    cookingTimeMinutes: 45,
    difficulty: "medium",
    moods: ["comforting", "hungry", "special", "craving"],
    mealTimes: ["lunch", "dinner"],
    instructions: [
      "Blend tomato, pepper and onion into a smooth base.",
      "Fry the blend in hot oil until the colour deepens.",
      "Add seasoning and curry, then stir.",
      "Add washed rice and water, cover and cook on low heat.",
      "Stir once, steam until soft, and serve.",
    ],
  },
  {
    id: "tomato-rice",
    name: "Tomato Rice",
    description: "A lighter, faster cousin of jollof. Bright and tangy.",
    ingredients: ["rice", "tomato", "onion", "pepper", "oil", "seasoning"],
    estimatedCostNgn: 1600,
    cookingTimeMinutes: 35,
    difficulty: "easy",
    moods: ["comforting", "quick", "hungry"],
    mealTimes: ["lunch", "dinner"],
    instructions: [
      "Blend tomato, onion and pepper.",
      "Fry the blend in oil for 5 minutes.",
      "Add seasoning and a little water.",
      "Add washed rice, cover and cook until soft.",
      "Fluff and serve.",
    ],
  },
  {
    id: "rice-and-egg-sauce",
    name: "Rice and Egg Sauce",
    description: "Plain rice with a rich tomato-egg sauce. Comfort in a plate.",
    ingredients: ["rice", "egg", "tomato", "onion", "pepper", "oil"],
    estimatedCostNgn: 1400,
    cookingTimeMinutes: 25,
    difficulty: "easy",
    moods: ["tired", "quick", "budget", "comforting"],
    mealTimes: ["breakfast", "lunch", "dinner"],
    instructions: [
      "Boil the rice.",
      "Fry onion and pepper in oil.",
      "Add chopped tomato and cook until soft.",
      "Pour in beaten egg, stir gently and cook through.",
      "Serve the sauce over the rice.",
    ],
  },
  {
    id: "rice-and-beans",
    name: "Rice and Beans",
    description: "Half rice, half beans. Properly filling and properly cheap.",
    ingredients: ["rice", "beans", "onion", "pepper", "oil", "seasoning"],
    estimatedCostNgn: 1700,
    cookingTimeMinutes: 50,
    difficulty: "easy",
    moods: ["hungry", "comforting", "budget"],
    mealTimes: ["lunch", "dinner"],
    instructions: [
      "Cook the beans until soft.",
      "Add washed rice to the pot.",
      "Add blended pepper and onion, oil and seasoning.",
      "Add water and cook until both are soft.",
      "Stir together and serve.",
    ],
  },
  {
    id: "coconut-rice",
    name: "Coconut Rice",
    description: "Rice cooked in coconut milk. Rich, fragrant, a little bit special.",
    ingredients: ["rice", "coconut", "onion", "pepper", "seasoning", "oil"],
    estimatedCostNgn: 2300,
    cookingTimeMinutes: 45,
    difficulty: "medium",
    moods: ["special", "craving", "happy"],
    mealTimes: ["lunch", "dinner"],
    instructions: [
      "Extract coconut milk from the grated coconut.",
      "Fry onion and pepper lightly in oil.",
      "Add the coconut milk and seasoning.",
      "Add washed rice and cook on low heat.",
      "Steam until soft and serve.",
    ],
  },
  {
    id: "pepper-rice",
    name: "Pepper Rice",
    description: "Rice with a serious pepper kick. Not for the faint-hearted.",
    ingredients: ["rice", "pepper", "onion", "tomato", "oil", "seasoning"],
    estimatedCostNgn: 2000,
    cookingTimeMinutes: 40,
    difficulty: "medium",
    moods: ["spicy", "craving", "hungry"],
    mealTimes: ["lunch", "dinner"],
    instructions: [
      "Blend pepper, onion and tomato coarsely.",
      "Fry the blend in hot oil until it darkens.",
      "Add seasoning and a splash of water.",
      "Add washed rice, cover and cook on low heat.",
      "Serve hot.",
    ],
  },
  {
    id: "sardine-rice",
    name: "Sardine Rice",
    description: "Rice and tinned sardine. Zero stress, plenty flavour.",
    ingredients: ["rice", "sardine", "onion", "pepper", "oil"],
    estimatedCostNgn: 1900,
    cookingTimeMinutes: 30,
    difficulty: "easy",
    moods: ["quick", "craving", "tired"],
    mealTimes: ["lunch", "dinner"],
    instructions: [
      "Boil the rice.",
      "Fry onion and pepper in oil.",
      "Add the sardine and break it up.",
      "Fold in the rice and stir well.",
      "Serve immediately.",
    ],
  },
  {
    id: "vegetable-fried-rice",
    name: "Vegetable Fried Rice",
    description: "Colourful, veg-packed rice. Feels like a proper treat.",
    ingredients: ["rice", "carrot", "green beans", "onion", "pepper", "oil", "seasoning"],
    estimatedCostNgn: 2200,
    cookingTimeMinutes: 35,
    difficulty: "medium",
    moods: ["hungry", "happy", "craving"],
    mealTimes: ["lunch", "dinner"],
    instructions: [
      "Boil the rice and set aside.",
      "Stir-fry carrot, green beans, onion and pepper.",
      "Add seasoning and a splash of water.",
      "Add the rice and toss everything together.",
      "Cover for 3 minutes and serve.",
    ],
  },
  {
    id: "one-pot-chicken-rice",
    name: "One-Pot Chicken Rice",
    description: "Chicken and rice in one pot. Big flavour, one pot to wash.",
    ingredients: ["rice", "chicken", "onion", "pepper", "tomato", "oil", "seasoning"],
    estimatedCostNgn: 3500,
    cookingTimeMinutes: 55,
    difficulty: "medium",
    moods: ["special", "comforting", "happy"],
    mealTimes: ["lunch", "dinner"],
    instructions: [
      "Season and brown the chicken in oil.",
      "Add blended tomato, pepper and onion. Fry well.",
      "Add water and bring to a boil.",
      "Add washed rice, cover and cook on low heat.",
      "Steam until soft and serve.",
    ],
  },

  // ───────────── NOODLES ─────────────
  {
    id: "egg-noodles",
    name: "Egg Noodles",
    description: "Noodles with egg. The 12-minute lifesaver.",
    ingredients: ["noodles", "egg", "onion", "pepper", "oil"],
    estimatedCostNgn: 900,
    cookingTimeMinutes: 12,
    difficulty: "easy",
    moods: ["tired", "quick", "budget", "hungry"],
    mealTimes: ["breakfast", "lunch", "dinner"],
    instructions: [
      "Boil the noodles with their seasoning.",
      "In another pan, fry onion and pepper in oil.",
      "Pour in the beaten egg and scramble.",
      "Add the cooked noodles and toss together.",
      "Serve hot.",
    ],
  },
  {
    id: "spicy-egg-noodles",
    name: "Spicy Egg Noodles",
    description: "Noodles, egg and extra pepper. Ready before you finish scrolling.",
    ingredients: ["noodles", "egg", "pepper", "onion", "oil", "seasoning"],
    estimatedCostNgn: 1300,
    cookingTimeMinutes: 15,
    difficulty: "easy",
    moods: ["spicy", "tired", "quick", "craving"],
    mealTimes: ["breakfast", "lunch", "dinner"],
    instructions: [
      "Boil the noodles until just soft.",
      "Heat oil and fry the pepper and onion.",
      "Add the beaten egg and scramble.",
      "Add the noodles and seasoning, stir well.",
      "Serve hot.",
    ],
  },
  {
    id: "stir-fried-noodles",
    name: "Stir-Fried Noodles",
    description: "Noodles with crunch. A small upgrade for very little effort.",
    ingredients: ["noodles", "carrot", "green beans", "onion", "pepper", "oil"],
    estimatedCostNgn: 1500,
    cookingTimeMinutes: 18,
    difficulty: "easy",
    moods: ["quick", "craving", "happy"],
    mealTimes: ["lunch", "dinner"],
    instructions: [
      "Boil the noodles and drain.",
      "Stir-fry carrot, green beans, onion and pepper on high heat.",
      "Add the noodles and seasoning.",
      "Toss for 2 minutes.",
      "Serve.",
    ],
  },
  {
    id: "sardine-noodles",
    name: "Sardine Noodles",
    description: "Noodles plus tinned sardine. Suddenly a real meal.",
    ingredients: ["noodles", "sardine", "onion", "pepper", "oil"],
    estimatedCostNgn: 1600,
    cookingTimeMinutes: 15,
    difficulty: "easy",
    moods: ["quick", "craving", "hungry"],
    mealTimes: ["lunch", "dinner"],
    instructions: [
      "Boil the noodles.",
      "Fry onion and pepper in oil.",
      "Add the sardine and mash it in.",
      "Add the noodles and seasoning, stir.",
      "Serve hot.",
    ],
  },
  {
    id: "chicken-noodles",
    name: "Chicken Noodles",
    description: "Noodles with shredded chicken. Feels like a promotion.",
    ingredients: ["noodles", "chicken", "onion", "pepper", "oil", "seasoning"],
    estimatedCostNgn: 2500,
    cookingTimeMinutes: 25,
    difficulty: "easy",
    moods: ["special", "happy", "comforting"],
    mealTimes: ["lunch", "dinner"],
    instructions: [
      "Cook and shred the chicken.",
      "Boil the noodles.",
      "Fry onion and pepper, then add the chicken.",
      "Add noodles and seasoning, toss together.",
      "Serve hot.",
    ],
  },
  {
    id: "vegetable-noodles",
    name: "Vegetable Noodles",
    description: "Noodles with vegetables stirred through. Lighter but still fast.",
    ingredients: ["noodles", "carrot", "green beans", "onion", "pepper", "oil"],
    estimatedCostNgn: 1400,
    cookingTimeMinutes: 18,
    difficulty: "easy",
    moods: ["quick", "happy"],
    mealTimes: ["lunch", "dinner"],
    instructions: [
      "Boil the noodles.",
      "Stir-fry the vegetables in oil.",
      "Add noodles and seasoning.",
      "Toss for 2 minutes.",
      "Serve.",
    ],
  },

  // ───────────── YAM ─────────────
  {
    id: "fried-yam-and-egg",
    name: "Fried Yam and Egg",
    description: "Crispy yam and a simple egg. A Nigerian classic.",
    ingredients: ["yam", "egg", "onion", "pepper", "oil"],
    estimatedCostNgn: 1500,
    cookingTimeMinutes: 25,
    difficulty: "easy",
    moods: ["tired", "comforting", "budget", "craving"],
    mealTimes: ["breakfast", "lunch", "dinner"],
    instructions: [
      "Peel and slice the yam.",
      "Fry the yam in hot oil until golden.",
      "Fry onion and pepper in a little oil.",
      "Add the beaten egg and cook through.",
      "Serve the egg with the yam.",
    ],
  },
  {
    id: "boiled-yam-and-egg-sauce",
    name: "Boiled Yam and Egg Sauce",
    description: "Soft boiled yam with a tomato-egg sauce. Gentle and filling.",
    ingredients: ["yam", "egg", "tomato", "onion", "pepper", "oil"],
    estimatedCostNgn: 1600,
    cookingTimeMinutes: 30,
    difficulty: "easy",
    moods: ["comforting", "hungry", "tired"],
    mealTimes: ["breakfast", "lunch", "dinner"],
    instructions: [
      "Boil the yam with a pinch of salt until soft.",
      "Fry onion and pepper in oil.",
      "Add chopped tomato and cook down.",
      "Pour in the beaten egg and stir gently.",
      "Serve the sauce over the yam.",
    ],
  },
  {
    id: "yam-porridge",
    name: "Yam Porridge",
    description: "Yam cooked soft in a peppery sauce. Proper comfort food.",
    ingredients: ["yam", "pepper", "onion", "spinach", "oil", "seasoning"],
    estimatedCostNgn: 1800,
    cookingTimeMinutes: 40,
    difficulty: "medium",
    moods: ["comforting", "hungry"],
    mealTimes: ["lunch", "dinner"],
    instructions: [
      "Peel and cube the yam.",
      "Add blended pepper and onion, oil and seasoning.",
      "Add water and cook until the yam softens.",
      "Mash a few pieces to thicken it.",
      "Stir in the spinach and simmer for 2 minutes.",
    ],
  },
  {
    id: "yam-and-pepper-sauce",
    name: "Yam and Pepper Sauce",
    description: "Boiled yam with a hot pepper dip. Simple, sharp, satisfying.",
    ingredients: ["yam", "pepper", "onion", "oil", "seasoning"],
    estimatedCostNgn: 1400,
    cookingTimeMinutes: 25,
    difficulty: "easy",
    moods: ["spicy", "quick", "budget"],
    mealTimes: ["breakfast", "lunch", "dinner"],
    instructions: [
      "Boil the yam until soft.",
      "Blend pepper and onion roughly.",
      "Fry the blend in hot oil.",
      "Add seasoning and a splash of water.",
      "Serve the sauce with the yam.",
    ],
  },

  // ───────────── BEANS ─────────────
  {
    id: "beans-porridge",
    name: "Beans Porridge",
    description: "Thick, peppery beans. Cheap, filling and always works.",
    ingredients: ["beans", "onion", "pepper", "oil", "seasoning"],
    estimatedCostNgn: 1300,
    cookingTimeMinutes: 50,
    difficulty: "easy",
    moods: ["comforting", "budget", "hungry"],
    mealTimes: ["breakfast", "lunch", "dinner"],
    instructions: [
      "Wash and cook the beans until soft.",
      "Add blended pepper and onion.",
      "Add oil and seasoning.",
      "Simmer until the water thickens.",
      "Serve hot.",
    ],
  },
  {
    id: "beans-and-plantain",
    name: "Beans and Plantain",
    description: "Beans and fried plantain. Sweet and savoury in one plate.",
    ingredients: ["beans", "plantain", "onion", "pepper", "oil"],
    estimatedCostNgn: 1700,
    cookingTimeMinutes: 45,
    difficulty: "easy",
    moods: ["hungry", "comforting", "craving"],
    mealTimes: ["lunch", "dinner"],
    instructions: [
      "Cook the beans with onion and pepper until soft.",
      "Season with oil and salt.",
      "Slice the plantain and fry until golden.",
      "Serve the plantain beside the beans.",
    ],
  },
  {
    id: "beans-and-bread",
    name: "Beans and Bread",
    description: "Beans porridge and bread. The original Nigerian struggle meal.",
    ingredients: ["beans", "bread", "onion", "pepper", "oil"],
    estimatedCostNgn: 1200,
    cookingTimeMinutes: 45,
    difficulty: "easy",
    moods: ["budget", "hungry", "tired"],
    mealTimes: ["breakfast", "lunch", "dinner"],
    instructions: [
      "Cook the beans with pepper and onion until soft.",
      "Add oil and seasoning, mash slightly.",
      "Slice the bread.",
      "Serve the beans with the bread.",
    ],
  },
  {
    id: "beans-and-garri",
    name: "Beans and Garri",
    description: "Beans and soaked garri. Zero cooking for the garri part.",
    ingredients: ["beans", "garri", "onion", "pepper", "oil"],
    estimatedCostNgn: 1100,
    cookingTimeMinutes: 45,
    difficulty: "easy",
    moods: ["budget", "hungry", "tired"],
    mealTimes: ["lunch", "dinner"],
    instructions: [
      "Cook the beans with pepper and onion until soft.",
      "Season with oil and salt.",
      "Soak the garri in cold water.",
      "Serve the beans with the garri.",
    ],
  },

  // ───────────── PASTA ─────────────
  {
    id: "jollof-spaghetti",
    name: "Jollof Spaghetti",
    description: "Spaghetti cooked in a tomato-pepper base. Everybody's favourite.",
    ingredients: ["spaghetti", "tomato", "pepper", "onion", "oil", "seasoning"],
    estimatedCostNgn: 1600,
    cookingTimeMinutes: 30,
    difficulty: "easy",
    moods: ["comforting", "hungry", "quick"],
    mealTimes: ["lunch", "dinner"],
    instructions: [
      "Blend tomato, pepper and onion.",
      "Fry the blend in oil until thick.",
      "Add seasoning and water, bring to a boil.",
      "Add the spaghetti and cook until soft.",
      "Serve hot.",
    ],
  },
  {
    id: "spaghetti-and-egg",
    name: "Spaghetti and Egg",
    description: "Spaghetti tossed with fried egg. Twenty minutes, no stress.",
    ingredients: ["spaghetti", "egg", "onion", "pepper", "oil"],
    estimatedCostNgn: 1300,
    cookingTimeMinutes: 20,
    difficulty: "easy",
    moods: ["tired", "quick", "budget"],
    mealTimes: ["breakfast", "lunch", "dinner"],
    instructions: [
      "Boil the spaghetti until soft and drain.",
      "Fry onion and pepper in oil.",
      "Add the beaten egg and scramble.",
      "Add the spaghetti and toss together.",
      "Serve hot.",
    ],
  },
  {
    id: "stir-fried-spaghetti",
    name: "Stir-Fried Spaghetti",
    description: "Spaghetti with vegetables, fried hard. Texture and flavour.",
    ingredients: ["spaghetti", "carrot", "green beans", "onion", "pepper", "oil"],
    estimatedCostNgn: 1800,
    cookingTimeMinutes: 30,
    difficulty: "medium",
    moods: ["craving", "happy", "hungry"],
    mealTimes: ["lunch", "dinner"],
    instructions: [
      "Boil the spaghetti and drain well.",
      "Stir-fry the vegetables on high heat.",
      "Add the spaghetti and seasoning.",
      "Toss for 3 minutes.",
      "Serve.",
    ],
  },
  {
    id: "sardine-spaghetti",
    name: "Sardine Spaghetti",
    description: "Spaghetti with tinned sardine in a tomato base.",
    ingredients: ["spaghetti", "sardine", "tomato", "onion", "pepper", "oil"],
    estimatedCostNgn: 1900,
    cookingTimeMinutes: 25,
    difficulty: "easy",
    moods: ["quick", "craving", "hungry"],
    mealTimes: ["lunch", "dinner"],
    instructions: [
      "Boil the spaghetti and drain.",
      "Fry onion, pepper and tomato in oil.",
      "Add the sardine and mash it in.",
      "Add the spaghetti and stir well.",
      "Serve hot.",
    ],
  },
  {
    id: "spicy-tomato-spaghetti",
    name: "Spicy Tomato Spaghetti",
    description: "Sharp, peppery spaghetti. For when you want to feel something.",
    ingredients: ["spaghetti", "tomato", "pepper", "onion", "oil", "seasoning"],
    estimatedCostNgn: 1700,
    cookingTimeMinutes: 25,
    difficulty: "easy",
    moods: ["spicy", "quick", "craving"],
    mealTimes: ["lunch", "dinner"],
    instructions: [
      "Blend tomato, pepper and onion.",
      "Fry the blend in hot oil until dark.",
      "Add seasoning and water.",
      "Cook the spaghetti in the sauce until soft.",
      "Serve hot.",
    ],
  },

  // ───────────── QUICK MEALS ─────────────
  {
    id: "egg-sandwich",
    name: "Egg Sandwich",
    description: "Bread, egg and pepper. Ten minutes, no cooking skill needed.",
    ingredients: ["bread", "egg", "butter", "onion", "pepper"],
    estimatedCostNgn: 1000,
    cookingTimeMinutes: 10,
    difficulty: "easy",
    moods: ["tired", "quick", "budget"],
    mealTimes: ["breakfast", "lunch"],
    instructions: [
      "Fry the egg with onion and pepper.",
      "Toast the bread lightly.",
      "Spread butter on the bread.",
      "Put the egg between the slices.",
      "Cut and serve.",
    ],
  },
  {
    id: "sardine-sandwich",
    name: "Sardine Sandwich",
    description: "Tinned sardine on bread. Basically zero effort, actually good.",
    ingredients: ["bread", "sardine", "onion", "pepper", "butter"],
    estimatedCostNgn: 1400,
    cookingTimeMinutes: 8,
    difficulty: "easy",
    moods: ["quick", "tired", "budget"],
    mealTimes: ["breakfast", "lunch"],
    instructions: [
      "Mash the sardine with onion and pepper.",
      "Spread butter on the bread.",
      "Add the sardine mix.",
      "Close the sandwich and serve.",
    ],
  },
  {
    id: "omelette-and-bread",
    name: "Omelette and Bread",
    description: "A proper omelette with bread on the side. Breakfast royalty.",
    ingredients: ["bread", "egg", "onion", "pepper", "oil"],
    estimatedCostNgn: 1100,
    cookingTimeMinutes: 12,
    difficulty: "easy",
    moods: ["tired", "quick", "budget", "hungry"],
    mealTimes: ["breakfast", "lunch"],
    instructions: [
      "Beat the eggs with onion and pepper.",
      "Heat oil in a pan.",
      "Pour in the egg and cook until set.",
      "Fold the omelette.",
      "Serve with bread.",
    ],
  },
  {
    id: "pepper-egg",
    name: "Pepper Egg",
    description: "Egg fried hard with plenty pepper. Small thing, big flavour.",
    ingredients: ["egg", "pepper", "onion", "oil"],
    estimatedCostNgn: 800,
    cookingTimeMinutes: 10,
    difficulty: "easy",
    moods: ["spicy", "quick", "budget"],
    mealTimes: ["breakfast", "lunch", "dinner"],
    instructions: [
      "Chop the pepper and onion.",
      "Heat oil in a pan.",
      "Add pepper and onion, fry for 1 minute.",
      "Pour in the beaten egg and fry until set.",
      "Serve hot.",
    ],
  },
  {
    id: "egg-and-plantain",
    name: "Egg and Plantain",
    description: "Fried plantain and egg. Sweet, savoury, done in 20.",
    ingredients: ["plantain", "egg", "onion", "pepper", "oil"],
    estimatedCostNgn: 1300,
    cookingTimeMinutes: 20,
    difficulty: "easy",
    moods: ["comforting", "quick", "craving"],
    mealTimes: ["breakfast", "lunch", "dinner"],
    instructions: [
      "Slice and fry the plantain until golden.",
      "Fry onion and pepper in a little oil.",
      "Add the beaten egg and cook through.",
      "Serve the egg with the plantain.",
    ],
  },
  {
    id: "bread-and-akara",
    name: "Bread and Akara",
    description: "Fresh akara and bread. The breakfast that never misses.",
    ingredients: ["bread", "beans", "onion", "pepper", "oil"],
    estimatedCostNgn: 900,
    cookingTimeMinutes: 25,
    difficulty: "medium",
    moods: ["budget", "hungry", "comforting"],
    mealTimes: ["breakfast"],
    instructions: [
      "Blend peeled beans with onion and pepper into a paste.",
      "Whip the paste so it traps air.",
      "Heat oil and scoop the paste in to fry.",
      "Fry until golden on both sides.",
      "Serve with bread.",
    ],
  },
  {
    id: "fried-plantain-and-egg",
    name: "Fried Plantain and Egg",
    description: "Dodo and egg. Twenty minutes and you're eating well.",
    ingredients: ["plantain", "egg", "onion", "pepper", "oil"],
    estimatedCostNgn: 1200,
    cookingTimeMinutes: 18,
    difficulty: "easy",
    moods: ["tired", "quick", "budget", "craving"],
    mealTimes: ["breakfast", "lunch", "dinner"],
    instructions: [
      "Fry the sliced plantain until golden.",
      "Fry onion and pepper in a separate pan.",
      "Add the beaten egg and scramble.",
      "Serve together.",
    ],
  },
  {
    id: "pap-and-egg",
    name: "Pap and Egg",
    description: "Warm pap with a boiled or fried egg. Gentle on the stomach.",
    ingredients: ["pap", "egg", "onion", "oil"],
    estimatedCostNgn: 900,
    cookingTimeMinutes: 15,
    difficulty: "easy",
    moods: ["tired", "comforting", "budget"],
    mealTimes: ["breakfast"],
    instructions: [
      "Mix the pap with a little cold water.",
      "Pour in hot water and stir until smooth.",
      "Fry the egg with onion.",
      "Serve the pap with the egg.",
    ],
  },
  {
    id: "pancakes",
    name: "Pancakes",
    description: "Fluffy pancakes. Sweet, soft and ready in 20 minutes.",
    ingredients: ["flour", "egg", "milk", "sugar", "butter"],
    estimatedCostNgn: 1200,
    cookingTimeMinutes: 20,
    difficulty: "easy",
    moods: ["happy", "craving", "quick"],
    mealTimes: ["breakfast"],
    instructions: [
      "Whisk flour, egg, milk and sugar into a smooth batter.",
      "Heat a pan and melt a little butter.",
      "Pour in a small scoop of batter.",
      "Flip when bubbles appear.",
      "Stack and serve.",
    ],
  },
  {
    id: "chicken-sandwich",
    name: "Chicken Sandwich",
    description: "Shredded chicken, mayo and bread. Feels like a treat.",
    ingredients: ["bread", "chicken", "mayonnaise", "onion", "pepper"],
    estimatedCostNgn: 2400,
    cookingTimeMinutes: 20,
    difficulty: "medium",
    moods: ["special", "happy", "craving"],
    mealTimes: ["breakfast", "lunch"],
    instructions: [
      "Cook and shred the chicken.",
      "Mix with mayonnaise, onion and pepper.",
      "Toast the bread lightly.",
      "Fill with the chicken mix.",
      "Cut and serve.",
    ],
  },
  {
    id: "indomie-and-sausage",
    name: "Indomie and Sausage",
    description: "Noodles, sausage and egg. The after-party classic.",
    ingredients: ["noodles", "sausage", "egg", "pepper", "oil"],
    estimatedCostNgn: 1100,
    cookingTimeMinutes: 12,
    difficulty: "easy",
    moods: ["tired", "quick", "budget", "craving"],
    mealTimes: ["breakfast", "lunch", "dinner"],
    instructions: [
      "Boil the noodles with seasoning.",
      "Slice and fry the sausage.",
      "Fry the egg in the same pan.",
      "Add the noodles and toss.",
      "Serve hot.",
    ],
  },

  // ───────────── SOUPS / SWALLOW ─────────────
  {
    id: "egusi-soup-and-garri",
    name: "Egusi Soup and Garri",
    description: "Thick melon-seed soup with garri. Heavy, proper, satisfying.",
    ingredients: ["egusi", "garri", "spinach", "pepper", "onion", "oil", "seasoning"],
    estimatedCostNgn: 2600,
    cookingTimeMinutes: 55,
    difficulty: "medium",
    moods: ["comforting", "hungry", "special"],
    mealTimes: ["lunch", "dinner"],
    instructions: [
      "Blend the egusi into a thick paste.",
      "Fry pepper and onion in palm oil.",
      "Add the egusi paste and fry until it firms up.",
      "Add water and seasoning, simmer for 15 minutes.",
      "Stir in the spinach and serve with garri.",
    ],
  },
  {
    id: "okra-soup-and-garri",
    name: "Okra Soup and Garri",
    description: "Drawy okra soup with garri. Fast as far as soups go.",
    ingredients: ["okra", "garri", "pepper", "onion", "oil", "seasoning"],
    estimatedCostNgn: 2300,
    cookingTimeMinutes: 45,
    difficulty: "medium",
    moods: ["comforting", "hungry"],
    mealTimes: ["lunch", "dinner"],
    instructions: [
      "Grate or blend the okra.",
      "Fry pepper and onion in oil.",
      "Add water and seasoning, bring to a boil.",
      "Add the okra and cook for 5 minutes only.",
      "Serve with garri.",
    ],
  },
  {
    id: "ogbono-soup-and-garri",
    name: "Ogbono Soup and Garri",
    description: "Drawy ogbono soup. Rich, smooth and very filling.",
    ingredients: ["ogbono", "garri", "pepper", "onion", "oil", "seasoning"],
    estimatedCostNgn: 2400,
    cookingTimeMinutes: 45,
    difficulty: "medium",
    moods: ["comforting", "hungry"],
    mealTimes: ["lunch", "dinner"],
    instructions: [
      "Fry pepper and onion in oil.",
      "Add water and bring to a boil.",
      "Sprinkle in the ogbono and stir well.",
      "Simmer until it thickens and draws.",
      "Serve with garri.",
    ],
  },
  {
    id: "achi-soup-and-garri",
    name: "Achi Soup and Garri",
    description: "Achi soup with garri. Deep, earthy and properly Eastern.",
    ingredients: ["achi", "garri", "pepper", "onion", "oil", "seasoning"],
    estimatedCostNgn: 2500,
    cookingTimeMinutes: 50,
    difficulty: "medium",
    moods: ["comforting", "special", "hungry"],
    mealTimes: ["lunch", "dinner"],
    instructions: [
      "Fry pepper and onion in oil.",
      "Add water and seasoning, bring to a boil.",
      "Add the achi and stir until it thickens.",
      "Simmer for 10 minutes.",
      "Serve with garri.",
    ],
  },
  {
    id: "efo-riro-and-garri",
    name: "Efo Riro and Garri",
    description: "Rich spinach stew with garri. Green, peppery and heavy.",
    ingredients: ["spinach", "pepper", "onion", "tomato", "oil", "seasoning", "garri"],
    estimatedCostNgn: 2400,
    cookingTimeMinutes: 45,
    difficulty: "medium",
    moods: ["hungry", "comforting", "spicy"],
    mealTimes: ["lunch", "dinner"],
    instructions: [
      "Blend pepper, onion and tomato.",
      "Fry the blend in oil until thick.",
      "Add seasoning and a little water.",
      "Stir in the chopped spinach and cook for 5 minutes.",
      "Serve with garri.",
    ],
  },

  // ───────────── POTATOES / OTHER ─────────────
  {
    id: "irish-potato-and-egg",
    name: "Irish Potato and Egg",
    description: "Boiled or fried potato with egg. Simple, soft, filling.",
    ingredients: ["potato", "egg", "onion", "pepper", "oil"],
    estimatedCostNgn: 1500,
    cookingTimeMinutes: 25,
    difficulty: "easy",
    moods: ["quick", "budget", "comforting"],
    mealTimes: ["breakfast", "lunch", "dinner"],
    instructions: [
      "Peel and boil or fry the potatoes.",
      "Fry onion and pepper in oil.",
      "Add the beaten egg and cook through.",
      "Serve the egg with the potatoes.",
    ],
  },
  {
    id: "potato-porridge",
    name: "Potato Porridge",
    description: "Potatoes cooked soft in a peppery sauce. Warm and easy.",
    ingredients: ["potato", "pepper", "onion", "oil", "seasoning"],
    estimatedCostNgn: 1700,
    cookingTimeMinutes: 35,
    difficulty: "easy",
    moods: ["comforting", "hungry"],
    mealTimes: ["lunch", "dinner"],
    instructions: [
      "Peel and cube the potatoes.",
      "Add blended pepper and onion, oil and seasoning.",
      "Add water and cook until soft.",
      "Mash a few pieces to thicken.",
      "Serve hot.",
    ],
  },
  {
    id: "potato-and-sardine",
    name: "Potato and Sardine",
    description: "Potatoes with tinned sardine. Quick, cheap and surprisingly good.",
    ingredients: ["potato", "sardine", "onion", "pepper", "oil"],
    estimatedCostNgn: 1800,
    cookingTimeMinutes: 25,
    difficulty: "easy",
    moods: ["quick", "craving", "budget"],
    mealTimes: ["lunch", "dinner"],
    instructions: [
      "Boil or fry the potatoes.",
      "Fry onion and pepper in oil.",
      "Add the sardine and break it up.",
      "Toss in the potatoes and stir.",
      "Serve hot.",
    ],
  },
  {
    id: "akara-and-pap",
    name: "Akara and Pap",
    description: "Golden bean cakes and warm pap. A proper morning.",
    ingredients: ["beans", "pap", "onion", "pepper", "oil"],
    estimatedCostNgn: 900,
    cookingTimeMinutes: 30,
    difficulty: "medium",
    moods: ["budget", "tired", "comforting"],
    mealTimes: ["breakfast"],
    instructions: [
      "Blend peeled beans with onion and pepper.",
      "Whip the paste until light.",
      "Fry scoops in hot oil until golden.",
      "Mix the pap with hot water.",
      "Serve together.",
    ],
  },
  {
    id: "moi-moi-and-pap",
    name: "Moi Moi and Pap",
    description: "Steamed bean pudding and pap. Soft, filling, gentle.",
    ingredients: ["beans", "pepper", "onion", "oil", "pap"],
    estimatedCostNgn: 1200,
    cookingTimeMinutes: 60,
    difficulty: "medium",
    moods: ["comforting", "happy"],
    mealTimes: ["breakfast", "lunch"],
    instructions: [
      "Blend peeled beans with pepper and onion.",
      "Add oil and stir the mixture well.",
      "Pour into lined cups or leaves.",
      "Steam for 40 minutes.",
      "Serve with warm pap.",
    ],
  },
];

export const MEALS_BY_ID = new Map(MEALS.map((m) => [m.id, m]));